---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: src/pages/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - portfolio-template
- type: document
  path: src/sections/profile.md
  label: Profile
- type: directory
  path: src/pages
  label: Page
  create: documents
  match: "*"
- type: directory
  path: src/pages/posts
  label: Post
  create: documents
  match: "**/*"
upload_dir: public/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/preview"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
